apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
      ver: v1.0
  template:
    metadata:
      labels:
        app: api
        ver: v1.0
    spec:
      containers:
        - name: api
          image: kandula17/devops-internal:master
          ports:
            - containerPort: 8082
#          env:
#          - name: DBHOST
#            value: "database-server-mariadb.default"
#          - name: DBUSER
#            value: "root"
#          - name: DBPASSWORD
#            valueFrom:
#              secretKeyRef:
#                name: database-server-mariadb
#                key: mariadb-root-password
#          - name: DBDATABASE
#            value: "events_db"


---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc
  name: api-svc
spec:
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8082
  selector:
    app: api
    ver: v1.0
  type: ClusterIP
